### ISSUE TITLE
Strapi Not Showing Editor.js 

### ISSUE THREAD

**Issue by jared-leddy** [melishev/strapi-plugin-react-editorjs#31]
The plugins section shows that it's installed, but it doesn't show up when trying to edit a post. I've tried to follow issue #27, and other issues, but nothing seems to work. What am I missing? What are the requirements for installation? 

The [Strapi docs](https://market.strapi.io/plugins/strapi-plugin-react-editorjs#install-now-section) state just adding the below code into the middlware.js file:

```js
module.exports = [
  // ...
  {
    name: 'strapi::security',
    config: {
      contentSecurityPolicy: {
        directives: {
          'img-src': ['*'],
        },
      }
    },
  },
  // ...
];
```

All efforts are not resulting in the editor being available.

**Comment by melishev** [comment]
Hello @jared-leddy .

Please provide more information about the version of strapi and plugin you are using.

**Comment by melishev** [comment]
Well, I'm closing this issue because I didn't get a response.

**Comment by jared-leddy** [comment]
Sorry, I didn't see the response.

**Comment by bavicj** [comment]
@melishev  I have the same issues, same strapi and plugin version.

**Comment by bavicj** [comment]
@jared-leddy I just switched from light to dark mode and it started to work

**Comment by jared-leddy** [comment]
> @jared-leddy I just switched from light to dark mode and it started to work

Thanks for the tip. It's frankly a silly solution, especially if it works, but I'll test it and post my results.

**Comment by jared-leddy** [comment]
@bavicj, once (this ticket)[https://github.com/strapi/strapi/issues/13085] is resolved I can test it.

**Comment by jared-leddy** [comment]
@bavicj & @melishev, FYI, ```npm run build``` was the fix.

**Comment by melishev** [comment]
@jared-leddy @bavicj 

this is very funny and strange, do I understand correctly that in dev mode with a dark theme, the Strapi plugin stops displaying?

**Comment by jared-leddy** [comment]
> @jared-leddy @bavicj
> 
> this is very funny and strange, do I understand correctly that in dev mode with a dark theme, the Strapi plugin stops displaying?

For me, once I ran the build script, it works in both light and dark modes.

**Comment by bavicj** [comment]
It is really strange, I did `yarn build` after plugin install and nothing happened, rich text fields still showed MD editor. After that I uninstalled and cloned directly as local plugin. This way it worked. So I removed local plugin, installed via yarn, build, and again original MD editor... Than I switched to dark mode and from nowhere it was working, rich text editor was editorjs..I tried again to uninstall/install and was not able to reproduce it..I think we could close this issue and see if someone else report something similar, or it was just glitch on my local env...

**Comment by dcakmak** [comment]
same problem here...

**Comment by kgrosvenor** [comment]
I've added some work for dark mode support, https://github.com/melishev/strapi-plugin-react-editorjs/issues/32 it now does support it, awaiting the PR to be merged ^^

**Comment by devmnj** [comment]
do you run the **yarn build** command ?

**Comment by jonathan-chin** [comment]
can confirm. after running `yarn build`, editorjs shows up. testing in light mode.

```
"@strapi/strapi": "4.1.12"
"strapi-plugin-react-editorjs": "^2.0.1"
```

**Comment by thedualspace** [comment]
> It is really strange, I did `yarn build` after plugin install and nothing happened, rich text fields still showed MD editor. After that I uninstalled and cloned directly as local plugin. This way it worked. So I removed local plugin, installed via yarn, build, and again original MD editor... Than I switched to dark mode and from nowhere it was working, rich text editor was editorjs..I tried again to uninstall/install and was not able to reproduce it..I think we could close this issue and see if someone else report something similar, or it was just glitch on my local env...

I am having the same problem, but opposite. 

When I install `yarn add strapi-plugin-react-editorjs` and run `yarn build`, I can use EditorJS. 

But when try I use a local clone of this repo, I get the default strapi editor. I can see the plugin listed in the plugins tab however? I need to use the local version because I need to add an EditorJS plugin for math typesetting.

My `config/plugins.ts` file looks like
```
export default {
  editorjs: {
    enabled: true,
    resolve: "./src/plugins/strapi-plugin-react-editorjs",
  },
};
```
And I have run `npm install` within the repo clone also.

Any ideas?

**Comment by thedualspace** [comment]
This miraculously solved itself once I left to do something else, after an hour or more of troubleshooting... Can't help but wonder if some cache in webpack or something is to blame

**Comment by chiwanpark** [comment]
I am having the same problem. When I install with `yarn add strapi-plugin-react-editor-js`, The EditorJS does not appear. After cloning the repository and configuring the plugin with the following settings, the editor appears.
```typescript
export default {
  editorjs: {
    enabled: true,
    resolve: "./src/plugins/strapi-plugin-react-editorjs",
  },
};
```

My dependencies list in `package.json` is as follows.
```json
"dependencies": {
  "@strapi/plugin-i18n": "4.3.8",
  "@strapi/plugin-users-permissions": "4.3.8",
  "@strapi/strapi": "4.3.8",
  "pg": "^8.8.0",
  "strapi-plugin-react-editorjs": "^2.0.2"
}
```

**Comment by b2storefront** [comment]
EditorJS does not display in the Dark mode, light mode solves that issue however on the UX in Admin where multiple EditorJS instances are used it randomly not loading some and they are being displayed but collapsed.
